version: "3"

services:
  labappkiii:
    depends_on:
      - postgres
    image: labapp.jar
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "8085:8085"

  postgres:
    image: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "user" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=emtlab2
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
